spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bishe?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
  mvc:
    dispatch-options-request: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000

  mail:
    host: smtp.qq.com
    username: 1443802862@qq.com
    password: osvrzlboyoingcid
    default-encoding: utf-8
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8080

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "PTSP " #token前缀
  secret: "20021221zyy" #密钥
  expireTime: 60 #token有效时间 (分钟) 建议一小时以上