spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bishe?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
  mvc:
    view:
      prefix: /jsps/
      suffix: .jsp
    dispatch-options-request: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8080